### ISSUE TITLE
Two different Nutri-Score at the same time

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/robotoff#355] opened 2021-08-12 10:44 UTC
For the following product, robotoff has applied two different Nutri-Score detections at the same time:
* Nutri-Score E: https://world.openfoodfacts.org/product/3760139470880/20-dont-4-oeufs-offerts-avibresse-dates-du-jour-de-ponte?rev=8
* Nutri-Score A: https://world.openfoodfacts.org/product/3760139470880/20-dont-4-oeufs-offerts-avibresse-dates-du-jour-de-ponte?rev=9

**Comment by teolemon** [comment] 2021-08-13 14:05
@CharlesNepote Your issue will be solved by solving: https://github.com/openfoodfacts/robotoff/issues/138

**Comment by teolemon** [comment] 2021-08-16 07:47
Also a duplicate of : https://github.com/openfoodfacts/robotoff/issues/115

**Comment by alexgarel** [comment] 2022-05-11 16:01
@teolemon why should we filter that. Those are only insight, we don't know which one is right, and it's up to a human to decide. How can we decide without one ?

**Comment by alexgarel** [comment] 2022-10-04 08:13
I close it as it does not seems like a real problem. (It's up to human to decide, moreover some products have more than one score).

**Closed by alexgarel** 2022-10-04 08:13 UTC
Labels: nutriscore model, does not require ML knowledge
