### ISSUE TITLE
Missing `source_image_url` attributes in some questions

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/robotoff#940] opened 2022-10-04 12:56 UTC
### What
Some questions do not have `source_image_url` For hunger games it's a problem because we are not able to know which image to display, and so have to skip the question

### Steps to reproduce the behavior:
1. Go to https://hunger.openfoodfacts.org/questions?type=product_weight&sorted=true and see it loads lot of pages before showing a quesitons
2. Or fetch https://robotoff.openfoodfacts.org/api/v1/questions/popular?count=260&lang=fr&insight_types=product_weight&page=1 and see that only questions after 250 have `source_image_url`

Of course answering hiungergame will increase the number of popular product without `source_image_url`

### Expected behavior
Either all of the questions have the attribute `source_image_url` or allows to filter them without having to loop on pages

**Comment by raphael0202** [comment] 2022-10-04 13:12
Product weight can be extracted from product names too, so it makes sense that there is no source image.
For information, here is the current number of unannotated insights with/without source image and with their corresponding data source:
 has_source_image | data_source    | count 
------------------+--------------+----------------------
 t                              |                         | 71051
 f                              | product_name |   899

I would be in favor on not displaying these questions on Hunger Games (see https://github.com/openfoodfacts/robotoff/issues/934 )

**Comment by raphael0202** [comment] 2022-10-12 09:39
As this is not a bug, I'm closing the issue.

**Closed by raphael0202** 2022-10-12 09:39 UTC
Labels: bug
