### ISSUE TITLE
Moderations alerts are broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#598] opened 2022-02-02 16:39 UTC
### What
- Moderations alerts are broken in moderation-off-alerts
- Might be related to the reopening of #495

**Comment by alexgarel** [comment] 2022-02-04 10:48
The problem is a deployment problem :
- we do not add SLACK_TOKEN in deploy action
- `ROBOTOFF_INSTANCE` is set to "org" instead of "prod"

I will release a hotfix for production

**Comment by alexgarel** [comment] 2022-02-04 11:13
This is done through the v1.1.0-hotfix1 tag.

We will need to merge the hotfixes branch in master https://github.com/openfoodfacts/robotoff/pull/601
But for now I'm testing in preprod.

**Comment by alexgarel** [comment] 2022-02-17 13:42
It's merged.

**Closed** 2022-02-17 13:42 UTC
Labels: notifications, ♞ epic, P0
